#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$files = new Illuminate\Filesystem\Filesystem;
$discovery = new Statamic\Translator\MethodDiscovery($files, [
    __DIR__.'/src',
    __DIR__.'/resources/js',
    __DIR__.'/resources/views'
]);

// Translation strings starting with these substrings will be ignored in stats.
$ignoredSubstrings = [
    'permissions.',
    'statamic::permissions.',
];

$app = new Symfony\Component\Console\Application('Statamic Translator');
$app->add(new Statamic\Translator\Commands\Generate($discovery, $files));
$app->add(new Statamic\Translator\Commands\Stats($discovery, $ignoredSubstrings));

$app->run();
