#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Statamic Translator');
$app->add(new Statamic\Translator\Commands\Stats);
$app->add(new Statamic\Translator\Commands\Generate);

$app->run();
