import { markRaw } from 'vue';
import Keys from './components/keys/Keys.js';
import Components from './components/Components.js';
import useGlobalEventBus from './composables/global-event-bus.js';
import useProgressBar from './composables/progress-bar.js';
import FieldActions from './components/field-actions/FieldActions.js';
import FieldConditions from './components/FieldConditions.js';
import Callbacks from './components/Callbacks.js';
import useDirtyState from './composables/dirty-state.js';
import Slugs from './components/slugs/Manager.js';
import Hooks from './components/Hooks.js';
import Bard from './components/Bard.js';
import Reveal from './components/Reveal.js';
import Echo from './components/Echo.js';
import Permission from './components/Permission.js';
import DateFormatter from './components/DateFormatter.js';
import CommandPalette from './components/CommandPalette.js';
import ColorMode from './components/ColorMode.js';
import Contrast from './components/Contrast.js';
import Config from './components/Config.js';
import Preferences from './components/Preference.js';
import Toasts from './components/Toasts.js';
import Portals from './components/portals/Portals.js';
import Stacks from './components/ui/Stack/Stacks.js';
import Inertia from './components/Inertia';

export const keys = new Keys();
export const components = new Components;
export const events = useGlobalEventBus();
export const progress = useProgressBar();
export const fieldActions = new FieldActions();
export const conditions = new FieldConditions();
export const callbacks = new Callbacks();
export const dirty = useDirtyState();
export const slug = new Slugs();
export const hooks = new Hooks();
export const bard = new Bard();
export const reveal = new Reveal();
export const echo = new Echo();
export const permissions = new Permission();
export const dateFormatter = new DateFormatter();
export const commandPalette = new CommandPalette();
export const colorMode = new ColorMode();
export const contrast = new Contrast();
export const config = new Config();
export const preferences = new Preferences();
export const toast = new Toasts();
export const portals = markRaw(new Portals());
export const stacks = new Stacks(portals);
export const inertia = new Inertia();
