export const {
    HasInputOptions,
    InlineEditForm,
    RelatedItem,
    ConfirmationModal,
    RevisionHistory,
    RestoreRevision,
    RevisionPreview,
    SaveButtonOptions,
    SortableList,
    HasPreferences,
    HasActions,
    resetValuesFromResponse,
    clone,
} = __STATAMIC__.temporary;
