import Vue from 'vue';
import orderby from '../filters/orderby';
import deslugify from '../filters/deslugify';
import markdown from '../filters/markdown';
import parse from '../filters/parse';
import pre from '../filters/pre';
import pluck from '../filters/pluck';
import reverse from '../filters/reverse';
import striptags from '../filters/striptags';
import titleize from '../filters/titleize';

Vue.filter('caseInsensitiveOrderBy', orderby);
Vue.filter('deslugify', deslugify);
Vue.filter('markdown', markdown);
Vue.filter('parse', parse);
Vue.filter('pre', pre);
Vue.filter('pluck', pluck);
Vue.filter('reverse', reverse);
Vue.filter('striptags', striptags);
Vue.filter('titleize', titleize);
