export function cp_url(url: any): any;
export function docs_url(url: any): any;
export function resource_url(url: any): any;
export function tidy_url(url: any): any;
export function relative_url(url: any): any;
export function dd(args: any): void;
export function data_get(obj: any, path: any, fallback?: null): any;
export function data_set(obj: any, path: any, value: any): void;
export function clone(value: any): any;
export function tailwind_width_class(width: any): string;
export function field_width_class(width: any): string;
export function markdown(value: any, options?: {}): "" | (import("trusted-types/lib").TrustedHTML & Node & DocumentFragment & string);
export function __(string: any, replacements: any): any;
export function __n(string: any, number: any, replacements: any): any;
export function utf8btoa(stringToEncode: any): string;
export function utf8atob(stringToDecode: any): string;
export function uniqid(): string;
export function truncate(string: any, length: any, ending?: string): any;
export function escapeHtml(string: any): any;
export function replicatorPreviewHtml(html: any): PreviewHtml;
export function str_slug(string: any): any;
export function snake_case(string: any): any;
import PreviewHtml from '../components/fieldtypes/replicator/PreviewHtml';
