<?php

namespace Statamic\Http\Controllers\CP\Collections;

use Illuminate\Http\Request;
use Statamic\Contracts\Entries\Entry as EntryContract;
use Statamic\Facades\Blink;
use Statamic\Facades\Entry;
use Statamic\Http\Controllers\CP\CpController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use function Statamic\trans as __;

class EntryTitleFormatController extends CpController
{
    public function create(Request $request, $collection, $site)
    {
        $this->authorize('create', [EntryContract::class, $collection, $site]);

        $this->ensureCollectionAutoGeneratesTitles($collection);

        $blueprint = $collection->entryBlueprint($request->blueprint);

        if (! $blueprint) {
            throw new \Exception(__('A valid blueprint is required.'));
        }

        $entry = Entry::make()
            ->collection($collection)
            ->blueprint($blueprint->handle())
            ->locale($site->handle());

        $values = $this->processedValues($blueprint, $request);

        if ($collection->dated() && $values->has('date')) {
            $entry->date($blueprint->field('date')->fieldtype()->augment($values->pull('date')));
        }

        return ['title' => $entry->data($values->except(['title', 'slug']))->autoGeneratedTitle()];
    }

    public function edit(Request $request, $collection, $entry)
    {
        $this->authorize('update', $entry);

        $this->ensureCollectionAutoGeneratesTitles($collection);

        $entry = $entry->fromWorkingCopy();

        if ($handle = $request->blueprint) {
            Blink::forget("entry-{$entry->id()}-blueprint");
            $entry->blueprint($handle);
        }

        $blueprint = $entry->blueprint();
        $values = $this->processedValues($blueprint, $request);

        if ($collection->dated() && $values->has('date')) {
            $entry->date($blueprint->field('date')->fieldtype()->augment($values->pull('date')));
        }

        return ['title' => $entry->merge($values->except(['title', 'slug']))->autoGeneratedTitle()];
    }

    private function ensureCollectionAutoGeneratesTitles($collection)
    {
        if (! $collection->autoGeneratesTitles()) {
            throw new NotFoundHttpException;
        }
    }

    private function processedValues($blueprint, $request)
    {
        $values = $request->input('values', []);

        // Only the fields the title format references get submitted, and processing
        // them fills in the rest, which would wipe out what the entry already has.
        return $blueprint
            ->fields()
            ->addValues($values)
            ->process()
            ->values()
            ->only(array_keys($values));
    }
}
