<?php

namespace Statamic\Http\Controllers\CP\Collections;

use Illuminate\Http\Request;
use Statamic\Contracts\Entries\Entry as EntryContract;
use Statamic\Facades\Entry;
use Statamic\Http\Controllers\CP\CpController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class EntryTitleFormatController extends CpController
{
    public function create(Request $request, $collection, $site)
    {
        $this->authorize('create', [EntryContract::class, $collection, $site]);

        $this->ensureCollectionAutoGeneratesTitles($collection);

        $blueprint = $collection->entryBlueprint($request->blueprint);
        $values = $this->processedValues($blueprint, $request);

        $entry = Entry::make()
            ->collection($collection)
            ->locale($site->handle());

        if ($collection->dated()) {
            $entry->date($blueprint->field('date')->fieldtype()->augment($values->pull('date')));
        }

        return ['title' => $entry->data($values->except(['title', 'slug']))->autoGeneratedTitle()];
    }

    public function edit(Request $request, $collection, $entry)
    {
        $this->authorize('update', $entry);

        $this->ensureCollectionAutoGeneratesTitles($collection);

        $entry = $entry->fromWorkingCopy();
        $values = $this->processedValues($blueprint = $entry->blueprint(), $request);

        if ($collection->dated() && $values->has('date')) {
            $entry->date($blueprint->field('date')->fieldtype()->augment($values->pull('date')));
        }

        return ['title' => $entry->merge($values->except(['title', 'slug']))->autoGeneratedTitle()];
    }

    private function ensureCollectionAutoGeneratesTitles($collection)
    {
        if (! $collection->autoGeneratesTitles()) {
            throw new NotFoundHttpException;
        }
    }

    private function processedValues($blueprint, $request)
    {
        return $blueprint
            ->fields()
            ->addValues($request->input('values', []))
            ->process()
            ->values();
    }
}
