<?php

namespace Statamic\Http\Controllers\CP\Collections;

use Illuminate\Http\Request;
use Statamic\Contracts\Entries\Entry as EntryContract;
use Statamic\Http\Controllers\CP\CpController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class EntryTitleFormatController extends CpController
{
    use MakesEntriesFromSubmittedValues;

    public function create(Request $request, $collection, $site)
    {
        $this->authorize('create', [EntryContract::class, $collection, $site]);

        $this->ensureCollectionAutoGeneratesTitles($collection);

        $entry = $this->makeEntryFromSubmittedValues($request, $collection, $site, ['title', 'slug']);

        return ['title' => $entry->autoGeneratedTitle()];
    }

    public function edit(Request $request, $collection, $entry)
    {
        $this->authorize('update', $entry);

        $this->ensureCollectionAutoGeneratesTitles($collection);

        $entry = $this->mergeSubmittedValuesIntoEntry($request, $collection, $entry, ['title', 'slug']);

        return ['title' => $entry->autoGeneratedTitle()];
    }

    private function ensureCollectionAutoGeneratesTitles($collection)
    {
        if (! $collection->autoGeneratesTitles()) {
            throw new NotFoundHttpException;
        }
    }
}
