<?php

namespace Statamic\Http\Controllers\CP\Collections;

use Illuminate\Http\Request;
use Statamic\Contracts\Entries\Entry as EntryContract;
use Statamic\Http\Controllers\CP\CpController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class EntrySlugFormatController extends CpController
{
    use MakesEntriesFromSubmittedValues;

    public function create(Request $request, $collection, $site)
    {
        $this->authorize('create', [EntryContract::class, $collection, $site]);

        $this->ensureCollectionAutoGeneratesSlugs($collection);

        $entry = $this->makeEntryFromSubmittedValues($request, $collection, $site, ['slug']);

        return ['slug' => $entry->autoGeneratedSlug()];
    }

    public function edit(Request $request, $collection, $entry)
    {
        $this->authorize('update', $entry);

        $this->ensureCollectionAutoGeneratesSlugs($collection);

        $entry = $this->mergeSubmittedValuesIntoEntry($request, $collection, $entry, ['slug']);

        return ['slug' => $entry->autoGeneratedSlug()];
    }

    private function ensureCollectionAutoGeneratesSlugs($collection)
    {
        if (! $collection->autoGeneratesSlugs()) {
            throw new NotFoundHttpException;
        }
    }
}
