export const keys: Keys;
export const components: Components;
export const events: {
    $on: (...args: any[]) => any;
    $once: (...args: any[]) => any;
    $off: (...args: any[]) => any;
    $emit: (...args: any[]) => any;
};
export const progress: {
    loading: (name: any, loading: any) => void;
    start: (name: any) => void;
    complete: (name: any) => void;
    names: () => never[];
    count: () => number;
    isComplete: () => boolean;
};
export const fieldActions: FieldActions;
export const conditions: FieldConditions;
export const callbacks: Callbacks;
export const dirty: {
    state: (name: any, state: any) => void;
    add: (name: any) => void;
    remove: (name: any) => void;
    names: () => never[];
    count: () => number;
    has: (name: any) => boolean;
    disableWarning: () => void;
};
export const slug: Slugs;
export const hooks: Hooks;
export const bard: Bard;
export const reveal: Reveal;
export const echo: Echo;
export const permissions: Permission;
export const dateFormatter: DateFormatter;
export const numberFormatter: NumberFormatter;
export const commandPalette: CommandPalette;
export const colorMode: ColorMode;
export const contrast: Contrast;
export const config: Config;
export const preferences: Preferences;
export const toast: Toasts;
export const portals: import("vue").Raw<Portals>;
export const stacks: Stacks;
export const inertia: Inertia;
import Keys from './components/keys/Keys.js';
import Components from './components/Components.js';
import FieldActions from './components/field-actions/FieldActions.js';
import FieldConditions from './components/FieldConditions.js';
import Callbacks from './components/Callbacks.js';
import Slugs from './components/slugs/Manager.js';
import Hooks from './components/Hooks.js';
import Bard from './components/Bard.js';
import Reveal from './components/Reveal.js';
import Echo from './components/Echo.js';
import Permission from './components/Permission.js';
import DateFormatter from './components/DateFormatter.js';
import NumberFormatter from './components/NumberFormatter.js';
import CommandPalette from './components/CommandPalette.js';
import ColorMode from './components/ColorMode.js';
import Contrast from './components/Contrast.js';
import Config from './components/Config.js';
import Preferences from './components/Preference.js';
import Toasts from './components/Toasts.js';
import Portals from './components/portals/Portals.js';
import Stacks from './components/ui/Stack/Stacks.js';
import Inertia from './components/Inertia';
