name: Lint code style issues

on:
  pull_request:

jobs:
  lint-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            **.php

      - name: Check PHP code style issues
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: aglipanci/laravel-pint-action@8eedec46a1856977c41667f9c66d5562fa3f9c08 # v2
        with:
          testMode: true
          verboseMode: true
          pintVersion: 1.16.0

      - name: Check Statamic\trans imports
        run: bash scripts/check-trans-import.sh
