name: Lint PHP code style issues

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  lint-php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Check PHP code style issues
        uses: aglipanci/laravel-pint-action@8eedec46a1856977c41667f9c66d5562fa3f9c08 # v2
        with:
          testMode: true
          verboseMode: true
          pintVersion: 1.16.0
