name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  fix-php-code-styling:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'statamic'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PINT }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@1.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
