name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Use Node.js 20.19.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20.19.0

      - name: Install dependencies
        run: npm ci

      - name: Build release assets
        run: bash ./scripts/build-release.sh

      - name: Get Changelog
        id: changelog
        uses: statamic/changelog-action@5d112d0d790cdeeb5adca3e584e37edc474ab51b # v1
        with:
          version: ${{ github.ref }}

      - name: Create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          release_name: ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.text }}
          prerelease: false

      - name: Upload dist zip to release
        uses: actions/upload-release-asset@64e5e85fc528f162d7ba7ce2d15a3bb67efb3d80 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist.tar.gz
          asset_name: dist.tar.gz
          asset_content_type: application/tar+gz

      - name: Upload dist-dev zip to release
        uses: actions/upload-release-asset@64e5e85fc528f162d7ba7ce2d15a3bb67efb3d80 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist-dev.tar.gz
          asset_name: dist-dev.tar.gz
          asset_content_type: application/tar+gz

      - name: Upload dist-frontend zip to release
        uses: actions/upload-release-asset@64e5e85fc528f162d7ba7ce2d15a3bb67efb3d80 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist-frontend.tar.gz
          asset_name: dist-frontend.tar.gz
          asset_content_type: application/tar+gz

      - name: Upload dist-package zip to release
        uses: actions/upload-release-asset@64e5e85fc528f162d7ba7ce2d15a3bb67efb3d80 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist-package.tar.gz
          asset_name: dist-package.tar.gz
          asset_content_type: application/tar+gz

      - name: Deploy Storybook to Forge
        continue-on-error: true
        run: |
          curl -X POST "${{ secrets.FORGE_STORYBOOK_WEBHOOK }}"
