name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js 20.19.0
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20.19.0

      - name: Install dependencies
        run: npm ci

      - name: Build release assets
        run: bash ./scripts/build-release.sh

      - name: Get Changelog
        id: changelog
        uses: statamic/changelog-action@5d112d0d790cdeeb5adca3e584e37edc474ab51b # v1
        with:
          version: ${{ github.ref }}

      - name: Create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          release_name: ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.text }}
          prerelease: false

      - name: Upload dist zip to release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist.tar.gz
          asset_name: dist.tar.gz
          asset_content_type: application/tar+gz

      - name: Upload dist-dev zip to release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist-dev.tar.gz
          asset_name: dist-dev.tar.gz
          asset_content_type: application/tar+gz

      - name: Upload dist-frontend zip to release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist-frontend.tar.gz
          asset_name: dist-frontend.tar.gz
          asset_content_type: application/tar+gz

      - name: Upload dist-package zip to release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist-package.tar.gz
          asset_name: dist-package.tar.gz
          asset_content_type: application/tar+gz

      - name: Deploy Storybook to Forge
        continue-on-error: true
        run: |
          curl -X POST "${{ secrets.FORGE_STORYBOOK_WEBHOOK }}"
