name: GitHub Actions Security Analysis

on:
  push:
    branches:
      - master
      - '*.x'
    paths:
      - '.github/**.yml'
  pull_request:
    paths:
      - '.github/**.yml'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    uses: statamic/.github/.github/workflows/global/zizmor.yml@bebe92309b4276e45ebc0d0c65854fb2ecf786ba
    permissions: {}
